version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "friday"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    # Labels on pull requests for version updates only
    labels:
      - "pip dependencies"
    assignees:
      - "sid7631"

  - package-ecosystem: "npm"
    directory: "/app/client"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "friday"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"
    assignees:
      - "sid7631"